services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"  # Optional: Qdrant web UI / metrics
    volumes:
      - qdrant_data:/qdrant/storage
    command: python -m rag_pipeline.qdrant_setup --input data/resume.json

  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - qdrant
    env_file:
      - .env
    environment:
      - QDRANT_HOST=http://qdrant:6333
    command: streamlit run app.py --server.port=8501 --server.enableCORS=false

volumes:
  qdrant_data:
